plugins {
    id 'java'
}

group 'com.boulderspace3d'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.badlogicgames.gdx:gdx:1.11.0'
    implementation 'com.google.inject:guice:5.1.0'
    implementation 'org.xerial:sqlite-jdbc:3.36.0.3'
}

sourceCompatibility = '1.8'
targetCompatibility = '1.8'